### ISSUE TITLE
Limit on the number of request of APIs

### ISSUE THREAD

**Issue by dravadhis** [WaltersArtMuseum/api-thewalters-org#74]
The API documentation mentions at (at-least) two places that the API puts a limit on the number of requests allowed per API key. 
1. This on the Accounts page after registering and logging in.
`To prevent abuse, the Walters Art Museum places limits on the number of API requests allowed per key.
Using a valid API key allows you to access data from the API and also helps prevent abuse.`

2. This is in the GitHub documentation [README.md]. [6th point.](https://github.com/WaltersArtMuseum/walters-api#general-specification-and-assumptions)
`The API has the ability to limit the amount of requests by API key to prevent abuse of the API.`

However nothing has been mentioned about what the limit is. It would be good if the documentation explicitly mentions the limit so that people using the API can send requests accordingly.

**Comment by dylan-k** [comment]
The limit is currently disabled, so I'll work to remove this confusing information. Thank you for pointing it out.
