### ISSUE TITLE
Inability to Log In and Unable to Call API

### ISSUE THREAD

**Issue by mgmauriello** [WaltersArtMuseum/api-thewalters-org#75]
I was testing my application which uses the Walters Art Museum API a few weeks ago and everything ran fine. Today while looking at my application, I received a 500 error. I test my GET request with my API key and nothing is fruitful. Go to the website and I receive this .net server error while trying to log in and even to make an account. 
________
**Server Error in '/' Application.**

**Description**: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

**Exception Details:** System.ComponentModel.Win32Exception: Access is denied

**Source Error:** An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
________

Screenshot of the entire error - 

![api thewalters org_SGAccount_Login](https://user-images.githubusercontent.com/97134047/176573354-fcd3a936-12a8-49e1-8e5d-3a4e8e322b88.png)

**Comment by mgmauriello** [comment]
@dylan-k still unable to log in, create an account, or return results in my application. The same server error appears when trying to log in / create account.
![api thewalters org_SGAccount_Register (1)](https://user-images.githubusercontent.com/97134047/177834998-f631cd5f-096f-493e-8b35-844c788c8f8d.png)

**Comment by AetherUnbound** [comment]
Hi there! We're also trying to set up a new account in order to reconnect our data as part of the Openverse project (see https://github.com/WordPress/openverse-catalog/issues/386). Is there any update available on this issue? I just tried making a new account and received the same error.

**Comment by johnbabb** [comment]
@dylan-k ,  I can confirm that this is a configuration issue at the database server level.  Please let us know if you need any help.
