### ISSUE TITLE
CollectionID inconsistent between art.csv and collections.csv

### ISSUE THREAD

**Issue by tacman** [WaltersArtMuseum/api-thewalters-org#80]
```csv
"CollectionID","CollectionName","CollDescription","NumObjects"
"1","Textiles and Furniture                                                                                                          ","","0"
"2","Southeast Asia                                                                                                           ","","264"
```

But in art.csv, the CollectionID is a string, and the collection name does not even exist in the collections.csv.

```
"EGY, JWL","Ancient Art",
```

Can you add the code from art.csv to the collections.csv table?  Or add the numeric ID to the art.csv table.  

Thanks for releasing this incredible set of data.

**Comment by tacman** [comment]
Alternatively, could you add an artwork_ids column, like you do with creators?

**Comment by dylan-k** [comment]
I think the simplest fix for now would be to use the ID, as expected. This could be instead of, or in addition to, the string.

Thanks for pointing out this inconsistency. I'll try to push up some revised CSV files ASAP.

**Comment by dylan-k** [comment]
I've revised the `collections.csv` data to use the same three-letter ID strings used by the `art.csv` file.
Thank you, @tacman, for bringing this to our attention.

**Comment by tacman** [comment]
Awesome, thanks!
