### ISSUE TITLE
Request for discussions

### ISSUE THREAD

**Issue by tacman** [WaltersArtMuseum/api-thewalters-org#81]
Since issues tend to be things that need to be resolved and closed, would you consider adding a "discussions" section which would allow more brainstorming and other things? 

In particular, I'm getting close to releasing a Spanish-language version of your collection and I wanted to provide a link and get feedback.  It's not really an "issue".

Gracias.

**Comment by dylan-k** [comment]
Yes, I agree that a place for discussion would be helpful. It would be great to hear from the data's users, and from you about your interesting project. I'll set that up as soon as I can, and will let you know.

**Comment by tacman** [comment]
I had a live link to this yesterday, but then ran out of disk space running the translations and am waiting for my sysops guy to clean it up.

![image](https://github.com/user-attachments/assets/c9165456-26b9-463b-a5a9-e1729bb0e5ff)

it'll be pretty cool when all the pieces are in place!

**Comment by dylan-k** [comment]
Discussions are open. 
https://github.com/WaltersArtMuseum/api-thewalters-org/discussions
