### ISSUE TITLE
Use of walters name, icon, etc.

### ISSUE THREAD

**Issue by tacman** [WaltersArtMuseum/api-thewalters-org#82]
I'm preparing to release a Spanish-language (and shortly others) version of your collection, and many others.

Of course, I'll provide attribution and links back to the site, but I'd also like to use some other content, like your name (for the title of the page) and perhaps a code if I decide to use subdomains, e.g. walters, walters-museum, walters-art, walters-art-museum. And a icon next to the data to reflect the source (that is, your museum).

Obviously, I can use what's on Wikipedia, but was wondering if there's something else available for people creating directories of museums.

Thanks.

**Comment by dylan-k** [comment]
The museum logo used on Wikipedia's pages is out of date. For example on [the commons page](https://commons.wikimedia.org/wiki/Commons:Walters_Art_Museum).

Would it be better to provide attribution without using a logo? Museums may prefer to reserve the use of their logo for official projects that began within or were officially conducted by the museum.

**Comment by dylan-k** [comment]
Although this form is initially designed for requesting high-resolution images in a printed context, you can use it to begin a conversation with our rights/permissions experts, who can better guide you on using our logo.
https://thewalters.org/about/policies/rights-reproductions/request/
